/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAdmin;
import ec.edu.ups.controlador.ControladorUsuario;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author braya
 */
public final class VntPrincipal extends javax.swing.JFrame {
    public static String ruta = "C:\\Users\\braya\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto_Interciclo\\registrarUsuario";
    //
    private ControladorUsuario ctrlUsuario;
    private ControladorAdmin ctrlAdmin;
    //
    private VntRegistrarAdmin vntRegistrarAdmin;
    private VntRegistrarUsuario vntRegistarUsuario;
    private VntIniciarsesion vntIniciar;
    private VntListarEstacionamientosOcupados vntListar;
    private VntReservar vntReservar;
    private VntRetirar vntRetirar;
    /**
     * Creates new form VntPrincipal
     */
    public VntPrincipal() {
        initComponents();
        //
        ctrlUsuario = ControladorUsuario.getInstancia();
        ctrlAdmin = ControladorAdmin.getInstancia();
        //
        vntRegistrarAdmin = new VntRegistrarAdmin(ctrlUsuario, ctrlAdmin, this);
        vntRegistarUsuario = new VntRegistrarUsuario(ctrlUsuario);
        vntIniciar = new VntIniciarsesion(ctrlUsuario, ctrlAdmin, this);
        vntListar = new VntListarEstacionamientosOcupados(ctrlAdmin, this);
        vntReservar = new VntReservar(ctrlUsuario, this);
        vntRetirar = new VntRetirar(ctrlAdmin, this);
        //
        getListarMenuItem().setVisible(false);
        getReservarMenuItem().setVisible(false);
        getRetirarMenuItem().setVisible(false);
    }

    public JMenuItem getRegistrarAdminMenuItem() {
        return registrarAdminMenuItem;
    }

    public JMenuItem getListarMenuItem() {
        return listarMenuItem;
    }

    public JMenuItem getReservarMenuItem() {
        return reservarMenuItem;
    }

    public JMenuItem getRetirarMenuItem() {
        return retirarMenuItem;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        registrarAdminMenuItem = new javax.swing.JMenuItem();
        registarUMenuItem = new javax.swing.JMenuItem();
        iniciarSesionMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        gestionMenu = new javax.swing.JMenu();
        listarMenuItem = new javax.swing.JMenuItem();
        reservarMenuItem = new javax.swing.JMenuItem();
        retirarMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setMnemonic('f');
        Menu.setText("Menu");

        registrarAdminMenuItem.setMnemonic('o');
        registrarAdminMenuItem.setText("Registrar Admin");
        registrarAdminMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAdminMenuItemActionPerformed(evt);
            }
        });
        Menu.add(registrarAdminMenuItem);

        registarUMenuItem.setMnemonic('s');
        registarUMenuItem.setText("Registrar Usuario");
        registarUMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarUMenuItemActionPerformed(evt);
            }
        });
        Menu.add(registarUMenuItem);

        iniciarSesionMenuItem.setMnemonic('a');
        iniciarSesionMenuItem.setText("Iniciar Sesion");
        iniciarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionMenuItemActionPerformed(evt);
            }
        });
        Menu.add(iniciarSesionMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        Menu.add(exitMenuItem);

        menuBar.add(Menu);

        gestionMenu.setMnemonic('e');
        gestionMenu.setText("Gestion");

        listarMenuItem.setMnemonic('t');
        listarMenuItem.setText("Listar  Contratos");
        listarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(listarMenuItem);

        reservarMenuItem.setMnemonic('y');
        reservarMenuItem.setText("Reservar");
        gestionMenu.add(reservarMenuItem);

        retirarMenuItem.setMnemonic('p');
        retirarMenuItem.setText("Retirar");
        gestionMenu.add(retirarMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        gestionMenu.add(deleteMenuItem);

        menuBar.add(gestionMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void registrarAdminMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAdminMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntRegistrarAdmin);
    }//GEN-LAST:event_registrarAdminMenuItemActionPerformed

    private void registarUMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarUMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntRegistarUsuario);
    }//GEN-LAST:event_registarUMenuItemActionPerformed

    private void iniciarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntIniciar);
    }//GEN-LAST:event_iniciarSesionMenuItemActionPerformed

    private void listarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntListar);
    }//GEN-LAST:event_listarMenuItemActionPerformed

    public void abrir(JInternalFrame frame) {
        desktopPane.add(frame);
        frame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VntPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu gestionMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem iniciarSesionMenuItem;
    private javax.swing.JMenuItem listarMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registarUMenuItem;
    private javax.swing.JMenuItem registrarAdminMenuItem;
    private javax.swing.JMenuItem reservarMenuItem;
    private javax.swing.JMenuItem retirarMenuItem;
    // End of variables declaration//GEN-END:variables

}
